### ISSUE TITLE
Casevalidator invalid regex

### ISSUE THREAD

**Issue by vlafranca** [epaew/eslint-plugin-filenames-simple#651]
## Describe the bug

The excepts attribute is not working with regex.

`ignorePattern.map(pattern => new RegExp(`^${pattern}$`))` there is unwanted $ at the beginning of the regex, the $ sign is only to match the last char.

## Expected behavior

Should be `ignorePattern.map(pattern => new RegExp(`^{pattern}$`))`  and match any regex.

**Comment by epaew** [comment]
First `$` is a part of syntax of the Template literals.
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

```js
 % node
Welcome to Node.js v18.10.0.
Type ".help" for more information.
> const pattern = "test";
undefined
> `^${pattern}$`;
'^test$'
>
```
